### PR TITLE
Postgres schema files

### PR DESCRIPTION
**Pull request by TaherKing**
Added postgres schema file for the certificates and verfication

### CODE REVIEW

**Comment by TaherKing** [comment]
Added the postgres schema files for the certificates and verification
 [https://github.com/Tibil-vishwAAs/Vishwaas/pull/33](url)

**Comment by TaherKing** [comment]
changed the certificates and verification schema file by including the IF NOT EXISTS operator
[https://github.com/Tibil-vishwAAs/Vishwaas/pull/33](url)

**Review by krishnakr6 — CHANGES_REQUESTED** [review]
Add primary in Verification table

**Comment by TaherKing** [comment]
Added primary key in the verification schema file [https://github.com/Tibil-vishwAAs/Vishwaas/pull/33](url)

**Review by krishnakr6 — APPROVED** [review]

**Review by krishnakr6 — CHANGES_REQUESTED** [review]
Remove .gitignore.swo file

**Review by krishnakr6 — APPROVED** [review]

**Pull request merged**
